import type { Lead } from "../types/lead";

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    source: "linkedin",
    author: "Sarah Chen",
    title: "VP Engineering, CloudScale AI",
    avatar: "SC",
    content: "Looking for CRM solutions that actually use AI for forecasting instead of manual data entry.",
    summary: "Strong frustration with manual entry. Great fit for SmartPredict workflows.",
    score: 98,
    tags: ["HOT SIGNAL", "BUDGET_CONFIRMED"],
    intent_label: "high",
    created_at: "2026-03-26T08:00:00Z",
    location: "San Francisco, CA",
    timeAgo: "2h ago",
    budget: true,
    urgency: true,
  },
  {
    id: "2",
    source: "twitter",
    author: "Marcus Thorne",
    title: "Founder, Velocity Ventures",
    avatar: "MT",
    content: "Scaling outbound from 10 to 50 reps. Need to maintain quality at high volume.",
    summary: "Expansion signal with immediate execution pressure.",
    score: 82,
    tags: ["EXPANSION"],
    intent_label: "high",
    created_at: "2026-03-26T06:00:00Z",
    location: "New York, NY",
    timeAgo: "5h ago",
    budget: true,
    urgency: false,
  },
  {
    id: "3",
    source: "reddit",
    author: "Jameson Holt",
    title: "Head of Sales, Nexus Group",
    avatar: "JH",
    content: "Tired of stale intent data. Most providers are giving lists from 3 months ago.",
    summary: "Freshness pain point. Live discovery is the differentiator here.",
    score: 76,
    tags: ["EXPANSION"],
    intent_label: "medium",
    created_at: "2026-03-25T13:00:00Z",
    location: "Austin, TX",
    timeAgo: "1d ago",
    budget: false,
    urgency: true,
  },
  {
    id: "4",
    source: "linkedin",
    author: "Priya Nambiar",
    title: "CTO, DataBridge Inc",
    avatar: "PN",
    content: "We are evaluating CRM replacements for Q3 and need Slack workflow integration.",
    summary: "Decision-maker with timeline and explicit integration requirement.",
    score: 91,
    tags: ["ENTERPRISE", "DECISION_MAKER"],
    intent_label: "high",
    created_at: "2026-03-26T05:00:00Z",
    location: "Boston, MA",
    timeAgo: "3h ago",
    budget: true,
    urgency: true,
  },
  {
    id: "5",
    source: "reddit",
    author: "Leo Carrasco",
    title: "Director of Growth, Finwave",
    avatar: "LC",
    content: "How do teams handle multi-channel prospecting without burning out SDRs?",
    summary: "Operational pain. Looking for automation tools.",
    score: 67,
    tags: ["EXPANSION"],
    intent_label: "medium",
    created_at: "2026-03-24T09:00:00Z",
    location: "Chicago, IL",
    timeAgo: "2d ago",
    budget: false,
    urgency: false,
  },
  {
    id: "6",
    source: "twitter",
    author: "Amara Osei",
    title: "CEO, Stackform",
    avatar: "AO",
    content: "Scaling B2B outbound workflows with AI. Has anyone automated the full sequence?",
    summary: "AI-forward mindset and immediate buying intent.",
    score: 88,
    tags: ["URGENT", "BUDGET_CONFIRMED"],
    intent_label: "high",
    created_at: "2026-03-26T04:00:00Z",
    location: "Seattle, WA",
    timeAgo: "6h ago",
    budget: true,
    urgency: true,
  },
];
